version: '3.8'

services:
  word-excel-replace:
    image: ghcr.io/${GITHUB_USERNAME:-MaroD1M}/Word-Replace:${TAG:-latest}
    container_name: Word-Replace
    network_mode: bridge
    ports:
      - "${EXTERNAL_PORT:-12344}:8501"
    restart: no
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    # 可选：数据持久化
    # volumes:
    #   - ./data:/app/data






